services:
  zoot:
    build: .
    container_name: zoot_game
    environment:
      - DISPLAY=host.docker.internal:0
      - XDG_RUNTIME_DIR=/tmp/runtime
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ./zoot
